version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_book_shop
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mysql:
    image: mysql:8.0.21
    container_name: mydb_book_shop
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb     # tự tạo DB rỗng
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  redis-data:
  mysql-data:
